---
:concurrency: 1
:queues:
  - default
  - mailers

  # Related to config.active_job.queue_name_prefix
  - daft_task_development_default
  - daft_task_development_mailers
  - daft_task_test_default
  - daft_task_test_mailers
